services:
  postgres_db:
    image: postgres:16.1
    container_name: destiny-postgres-cnt
    environment:
      POSTGRES_PASSWORD: destiny-pass
      POSTGRES_USER: destiny-user
      POSTGRES_DB: destiny_db
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - destiny-net

  server:
    build: ./app-server
    container_name: destiny-server-cnt
    ports:
      - 4000:4000
    volumes:
      # - /home/msm-faraj/Code/Public/Destiny/app-server/src:/app-server/src
      - ./app-server/src:/app-server/src

    networks:
      - destiny-net

  client:
    build: ./app-client
    container_name: destiny-client-cnt
    ports:
      - 3000:3000
    volumes:
      # - /home/msm-faraj/Code/Public/Destiny/app-client/src:/app-client/src
      # - /home/msm-faraj/Code/Public/Destiny/app-client/public:/app-client/public
      - ./app-client/src:/app-client/src
      - ./app-client/public:/app-client/public
    networks:
      - destiny-net
volumes:
  postgres_db:

networks:
  destiny-net:
    driver: "bridge"
