services:
  postgres_db:
    image: postgres:16.1
    container_name: app-postgres-cnt
    environment:
      POSTGRES_PASSWORD: app-pass
      POSTGRES_USER: app-user
      POSTGRES_DB: app_db
    ports:
      - 5000:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - app_net

  server:
    build: ./app-server
    container_name: app-server-cnt
    ports:
      - 4000:4000
    volumes:
      - ./app-server:/app-server
    networks:
      - app_net

  client:
    build: ./app-client
    container_name: app-client-cnt
    ports:
      - 3000:3000
    volumes:
      - ./app-client:/app-client
    networks:
      - app_net

volumes:
  postgres_db:

networks:
  app_net:
    driver: "bridge"
