services:
  postgres_db:
    image: postgres:16.1
    restart: always
    container_name: destiny-postgres-cnt
    environment:
      POSTGRES_PASSWORD: destiny-pass
      POSTGRES_USER: destiny-user
      POSTGRES_DB: destiny_db
    ports:
      - 5432:5432
    volumes:
      - data_pg:/var/lib/postgresql/data
    networks:
      - destiny-net

  server:
    build: ./app-server
    container_name: destiny-server-cnt
    ports:
      - 4040:4040
    volumes:
      - ./app-server:/app-server

    networks:
      - destiny-net

  client:
    build: ./app-client
    container_name: destiny-client-cnt
    ports:
      - 5173:5173
      - 3010:3010
    volumes:
      - ./app-client:/app-client
    networks:
      - destiny-net
volumes:
  data_pg:

networks:
  destiny-net:
    driver: "bridge"
